{% set name = "esi-acme" %}
{% set version = "2023.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/esi-acme-{{ version }}.tar.gz
  sha256: 10f140ff169b96565cbb824982123e71df707792e37e0329e2acdeeb3171a1d8

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pyyaml
    - toml
  run:
    - cloudpickle <=2.2.1
    - colorama
    - dask >=2021.09.0, <=2023.12
    - dask-jobqueue >=0.8,<0.9
    - h5py <4
    - numpy >=1.0,<2.0
    - pip
    - psutil
    - python >={{ python_min }},<3.13
    - msgpack-python <1.0.7
    - toolz >=0.12
    - tqdm >=4.31

test:
  imports:
    - acme
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://esi-acme.readthedocs.io/en/latest/
  summary: Asynchronous Computing Made ESI
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pantaray
