{% set name = "esi-acme" %}
{% set version = "2022.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/esi-acme-{{ version }}.tar.gz
  sha256: cd491573fca2f14e0a657ec0bcb7d10a693a38e8fbcb6a9be56770a45835b32d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<3.11
    - pyyaml
    - setuptools-scm
    - toml
  run:
    - click <8.1
    - colorama
    - dask <2022.11
    - dask-jobqueue >=0.8,<0.9
    - h5py <4
    - numpy >=1.0,<2.0
    - pip
    - psutil
    - python >=3.7,<3.11
    - tqdm >=4.31

test:
  imports:
    - acme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://esi-acme.readthedocs.io/en/latest/
  summary: Asynchronous Computing Made ESI
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pantaray
