{% set name = "esi-acme" %}
{% set version = "2023.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/esi-acme-{{ version }}.tar.gz
  sha256: 6d67e94964f4628f18253e732a71e528ecee5ddbefc0641e759097131afb33f6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<3.11
    - pyyaml
    - setuptools-scm
    - toml
  run:
    - colorama
    - dask >=2021.09.0, <2023.4
    - dask-jobqueue >=0.8,<0.9
    - h5py <4
    - numpy >=1.0,<2.0
    - pip
    - psutil
    - python >=3.7,<3.11
    - tqdm >=4.31

test:
  imports:
    - acme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://esi-acme.readthedocs.io/en/latest/
  summary: Asynchronous Computing Made ESI
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pantaray
