{% set name = "esi-acme" %}
{% set version = "0.2rc2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/esi-acme-{{ version }}.tar.gz
  sha256: 28ea56aa84f69d767dbe58d6093ee8d4e4583a3379934d980dfd49b2edd86d4b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
    - ruamel.yaml >=0.16,<0.17
  run:
    - bokeh
    - colorama
    - dask-core >=2.25,<2.26
    - dask-jobqueue >=0.7.1,<0.8
    - distributed >=2.25,<2.26
    - fsspec >=0.3.3
    - click <8.0
    - h5py >=2.9,<3
    - numpy >=1.0,<2.0
    - pip
    - python >=3.7
    - tqdm >=4.31

test:
  imports:
    - acme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://esi-acme.readthedocs.io/en/latest/
  summary: Asynchronous Computing Made ESI
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pantaray
