{% set name = "esi-acme" %}
{% set version = "0.20" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/esi-acme-{{ version }}.tar.gz
  sha256: 9ef471d2fde39f7c01d8f2f214d598b444615c04cc09b1a51c8f0b0e5a4b9793

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<3.9
    - setuptools-scm
    - ruamel.yaml >=0.16,<0.17
  run:
    - dask <2021.12
    - dask-jobqueue >=0.7.1,<0.8
    - h5py >=2.9,<3
    - numpy >=1.0,<2.0
    - pip
    - python >=3.7
    - tqdm >=4.31

test:
  imports:
    - acme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://esi-acme.readthedocs.io/en/latest/
  summary: Asynchronous Computing Made ESI
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pantaray
