{% set name = "esi-acme" %}
{% set version = "2022.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/esi-acme-{{ version }}.tar.gz
  sha256: 911ebc0d17f663f3499e84fcdf4f8cdb9908fc780ab120109fb6a145420665e9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<3.9
    - setuptools-scm
    - pyyaml
  run:
    - colorama
    - dask <2022.6
    - dask-jobqueue >=0.7.1,<0.8
    - h5py >=2.9,<3
    - numpy >=1.0,<2.0
    - pip
    - psutil
    - python >=3.7
    - tqdm >=4.31

test:
  imports:
    - acme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://esi-acme.readthedocs.io/en/latest/
  summary: Asynchronous Computing Made ESI
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pantaray
