{% set name = "esi-acme" %}
{% set version = "2025.3" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: be9d87a4f6a68a3a1002ae369b3a66ce761b13ae97657c944cf24c8ab5fbdfd7

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pyyaml
    - toml
    - setuptools
  run:
    - cloudpickle >2.2
    - dask >=2022.12.1,<=2024.12.1
    - dask-jobqueue >=0.8,<1.0
    - h5py >=3,<4
    - numpy >=1.0,<3.0
    - pip
    - psutil
    - python >={{ python_min }},<3.14
    - toolz >=0.12
    - tqdm >=4.31

test:
  imports:
    - acme
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://esi-acme.readthedocs.io/en/latest/
  summary: Asynchronous Computing Made ESI
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pantaray
