{% set name = "esi-acme" %}
{% set version = "2025.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 609a4e78f419ff84de2c6a1eb8713b56660e452edc59202d7c3f19a0373309eb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<3.13
    - pyyaml
    - toml
  run:
    - cloudpickle <=2.2.1
    - colorama
    - dask >=2021.09.0, <=2023.12
    - dask-jobqueue >=0.8,<0.9
    - h5py <4
    - numpy >=1.0,<2.0
    - pip
    - psutil
    - python >=3.7,<3.13
    - msgpack-python <1.0.7
    - toolz >=0.12
    - tqdm >=4.31

test:
  imports:
    - acme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://esi-acme.readthedocs.io/en/latest/
  summary: Asynchronous Computing Made ESI
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pantaray
